/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.songkhla.wordgen;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.json.simple.JSONObject;
import java.awt.image.BufferedImage;
import java.io.File;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Computer
 */
public class MainMenuWord extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuWord
     */
    Connection con=null;
        PreparedStatement pst=null;

    JPanel [] panel1;
    public MainMenuWord() {
        initComponents(); 
//        checkdata();
        ImageIcon img = new ImageIcon("D://Master//WD.png");
        setIconImage(img.getImage());
        setTitle("ระบบสำนวนอิเล็คทรอนิกส์ (CRIMES)");
       
//        CalculateDate();
        data();
//        setIconImage(Toolkit.getDefaultToolkit().getImage(MainMenuWord.class.getResource("D://Master//user.png")));
        pack();
        setLocationRelativeTo(null); 
        panel1 = new JPanel[]{personmenu,formmenu,howtomenu};
        setMaximumSize(new Dimension(1280, 720));
        setMinimumSize(new Dimension(1280, 720));
        setMaximizedBounds ( new Rectangle ( 1280, 720 ) );
        
        con=ConnectDatabase.connect();
        CreateTable.createNewTable();      

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        policemenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        personmenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profilemenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        formmenu = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        howtomenu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        SueMenu = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BailMenu = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        howtomenu1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        jPanelSueMenu = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanelBailMenu = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanelDocMenu = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setResizable(false);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(41, 100, 138));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel7.setForeground(new java.awt.Color(0, 86, 167));
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Master\\E-DOC2.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 193));

        jPanel2.setBackground(new java.awt.Color(4, 93, 179));
        jPanel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 500));

        policemenu.setBackground(new java.awt.Color(4, 93, 179));
        policemenu.setPreferredSize(new java.awt.Dimension(155, 54));
        policemenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                policemenuMouseMoved(evt);
            }
        });
        policemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policemenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                policemenuMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ข้อมูลสถานีตำรวจ");

        javax.swing.GroupLayout policemenuLayout = new javax.swing.GroupLayout(policemenu);
        policemenu.setLayout(policemenuLayout);
        policemenuLayout.setHorizontalGroup(
            policemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, policemenuLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(50, 50, 50))
        );
        policemenuLayout.setVerticalGroup(
            policemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(policemenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        personmenu.setBackground(new java.awt.Color(4, 93, 179));
        personmenu.setPreferredSize(new java.awt.Dimension(155, 54));
        personmenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                personmenuMouseMoved(evt);
            }
        });
        personmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personmenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                personmenuMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Master\\group (1).png")); // NOI18N
        jLabel1.setText("ข้อมูลบุคคล");

        javax.swing.GroupLayout personmenuLayout = new javax.swing.GroupLayout(personmenu);
        personmenu.setLayout(personmenuLayout);
        personmenuLayout.setHorizontalGroup(
            personmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personmenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
        );
        personmenuLayout.setVerticalGroup(
            personmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        profilemenu.setBackground(new java.awt.Color(4, 93, 179));
        profilemenu.setPreferredSize(new java.awt.Dimension(145, 54));
        profilemenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                profilemenuMouseMoved(evt);
            }
        });
        profilemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilemenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilemenuMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ข้อมูลผู้ใช้");

        javax.swing.GroupLayout profilemenuLayout = new javax.swing.GroupLayout(profilemenu);
        profilemenu.setLayout(profilemenuLayout);
        profilemenuLayout.setHorizontalGroup(
            profilemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilemenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(73, 73, 73))
        );
        profilemenuLayout.setVerticalGroup(
            profilemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilemenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        formmenu.setBackground(new java.awt.Color(4, 93, 179));
        formmenu.setPreferredSize(new java.awt.Dimension(149, 54));
        formmenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formmenuMouseMoved(evt);
            }
        });
        formmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formmenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formmenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formmenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formmenuMouseReleased(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Master\\document.png")); // NOI18N
        jLabel18.setText("แบบฟอร์ม");

        javax.swing.GroupLayout formmenuLayout = new javax.swing.GroupLayout(formmenu);
        formmenu.setLayout(formmenuLayout);
        formmenuLayout.setHorizontalGroup(
            formmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formmenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(60, 60, 60))
        );
        formmenuLayout.setVerticalGroup(
            formmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        howtomenu.setBackground(new java.awt.Color(4, 93, 179));
        howtomenu.setPreferredSize(new java.awt.Dimension(136, 54));
        howtomenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                howtomenuMouseMoved(evt);
            }
        });
        howtomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                howtomenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                howtomenuMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ข้อมูลพื้นฐาน");

        javax.swing.GroupLayout howtomenuLayout = new javax.swing.GroupLayout(howtomenu);
        howtomenu.setLayout(howtomenuLayout);
        howtomenuLayout.setHorizontalGroup(
            howtomenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, howtomenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(62, 62, 62))
        );
        howtomenuLayout.setVerticalGroup(
            howtomenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howtomenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        SueMenu.setBackground(new java.awt.Color(4, 93, 179));
        SueMenu.setPreferredSize(new java.awt.Dimension(147, 54));
        SueMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SueMenuMouseMoved(evt);
            }
        });
        SueMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SueMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SueMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SueMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SueMenuMouseReleased(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ผัดฟ้องฝากขัง");

        javax.swing.GroupLayout SueMenuLayout = new javax.swing.GroupLayout(SueMenu);
        SueMenu.setLayout(SueMenuLayout);
        SueMenuLayout.setHorizontalGroup(
            SueMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SueMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(58, 58, 58))
        );
        SueMenuLayout.setVerticalGroup(
            SueMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SueMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        BailMenu.setBackground(new java.awt.Color(4, 93, 179));
        BailMenu.setPreferredSize(new java.awt.Dimension(122, 54));
        BailMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BailMenuMouseMoved(evt);
            }
        });
        BailMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BailMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BailMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BailMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BailMenuMouseReleased(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ประกัน");

        javax.swing.GroupLayout BailMenuLayout = new javax.swing.GroupLayout(BailMenu);
        BailMenu.setLayout(BailMenuLayout);
        BailMenuLayout.setHorizontalGroup(
            BailMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BailMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(82, 82, 82))
        );
        BailMenuLayout.setVerticalGroup(
            BailMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BailMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        howtomenu1.setBackground(new java.awt.Color(4, 93, 179));
        howtomenu1.setPreferredSize(new java.awt.Dimension(136, 54));
        howtomenu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                howtomenu1MouseMoved(evt);
            }
        });
        howtomenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                howtomenu1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                howtomenu1MouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Master\\information.png")); // NOI18N
        jLabel16.setText("วิธีใช้");

        javax.swing.GroupLayout howtomenu1Layout = new javax.swing.GroupLayout(howtomenu1);
        howtomenu1.setLayout(howtomenu1Layout);
        howtomenu1Layout.setHorizontalGroup(
            howtomenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, howtomenu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(74, 74, 74))
        );
        howtomenu1Layout.setVerticalGroup(
            howtomenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howtomenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personmenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(profilemenu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(policemenu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(formmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(SueMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(BailMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(howtomenu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(howtomenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(profilemenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(policemenu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(personmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SueMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BailMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(formmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(howtomenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(howtomenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, -1, 520));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, new java.awt.Color(204, 204, 204)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Master\\1-1.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel9.setText("คดีอาญา");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel11.setText("ชันสูตร");

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Master\\3-1.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel13.setText("คดีจราจร");

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Master\\2-1.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel2.setText("ชื่อผู้ใช้ :");

        UserName.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        UserName.setForeground(new java.awt.Color(24, 19, 37));
        UserName.setText("Name");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelSueMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSueMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSueMenuMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\Master\\6-1.png")); // NOI18N

        jLabel19.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel19.setText("ผัดฟ้องฝากขัง");

        javax.swing.GroupLayout jPanelSueMenuLayout = new javax.swing.GroupLayout(jPanelSueMenu);
        jPanelSueMenu.setLayout(jPanelSueMenuLayout);
        jPanelSueMenuLayout.setHorizontalGroup(
            jPanelSueMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSueMenuLayout.createSequentialGroup()
                .addGroup(jPanelSueMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSueMenuLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel17))
                    .addGroup(jPanelSueMenuLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel19)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelSueMenuLayout.setVerticalGroup(
            jPanelSueMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSueMenuLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBailMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBailMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBailMenuMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\Master\\4-1.png")); // NOI18N

        jLabel21.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel21.setText("ประกัน");

        javax.swing.GroupLayout jPanelBailMenuLayout = new javax.swing.GroupLayout(jPanelBailMenu);
        jPanelBailMenu.setLayout(jPanelBailMenuLayout);
        jPanelBailMenuLayout.setHorizontalGroup(
            jPanelBailMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBailMenuLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanelBailMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBailMenuLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBailMenuLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(48, 48, 48))))
        );
        jPanelBailMenuLayout.setVerticalGroup(
            jPanelBailMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBailMenuLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDocMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDocMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDocMenuMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon("D:\\Master\\9-1.png")); // NOI18N

        jLabel23.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel23.setText("แบบฟอร์ม");

        javax.swing.GroupLayout jPanelDocMenuLayout = new javax.swing.GroupLayout(jPanelDocMenu);
        jPanelDocMenu.setLayout(jPanelDocMenuLayout);
        jPanelDocMenuLayout.setHorizontalGroup(
            jPanelDocMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocMenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel22)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDocMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(77, 77, 77))
        );
        jPanelDocMenuLayout.setVerticalGroup(
            jPanelDocMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocMenuLayout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSueMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBailMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDocMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelSueMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBailMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDocMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 217, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 727, 1280, -1));

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        CrimesCaseOverView ccv =new CrimesCaseOverView();
        ccv.pack();
        ccv.setLocationRelativeTo(null);
        ccv.setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked
 private static ImageIcon loadImageIcon(String path) {
        URL imgURL = MainMenuWord.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
         IdentityView idt = new IdentityView();
         idt.pack();
         idt.setLocationRelativeTo(null);
        idt.setVisible(true);
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
                // TODO add your handling code here:
        TrafficOverView trv =new TrafficOverView();
        trv.pack();
        trv.setLocationRelativeTo(null);
        trv.setVisible(true);
            
    }//GEN-LAST:event_jPanel11MouseClicked

    private void formmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formmenuMousePressed
            // TODO add your handling code here:


    }//GEN-LAST:event_formmenuMousePressed

    private void formmenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formmenuMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_formmenuMouseReleased

    private void formmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formmenuMouseClicked
        // TODO add your handling code here:
         JFrame frame = new JFrame();
        JDialog dialog = new JDialog(frame);//frame is owner
        JFrame in = (JFrame)(dialog.getParent());
        in.removeAll();
    ReportAllForm rf =new ReportAllForm(this,null);
        rf.pack();
        rf.setLocationRelativeTo(null);
        rf.setVisible(true);
    }//GEN-LAST:event_formmenuMouseClicked

    private void howtomenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtomenuMouseMoved
        // TODO add your handling code here:
        setPanelBackground(howtomenu);
    }//GEN-LAST:event_howtomenuMouseMoved

    private void howtomenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtomenuMouseExited
        // TODO add your handling code here:
        resetPanelBackground(howtomenu);
    }//GEN-LAST:event_howtomenuMouseExited

    private void formmenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formmenuMouseMoved
        // TODO add your handling code here:
        setPanelBackground(formmenu);
    }//GEN-LAST:event_formmenuMouseMoved

    private void formmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formmenuMouseExited
        // TODO add your handling code here:
         resetPanelBackground(formmenu);
    }//GEN-LAST:event_formmenuMouseExited

    private void personmenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personmenuMouseMoved
        // TODO add your handling code here:
         setPanelBackground(personmenu);
    }//GEN-LAST:event_personmenuMouseMoved

    private void personmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personmenuMouseExited
        // TODO add your handling code here:
        resetPanelBackground(personmenu);
    }//GEN-LAST:event_personmenuMouseExited

    private void policemenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policemenuMouseMoved
        // TODO add your handling code here:
         setPanelBackground(policemenu);
    }//GEN-LAST:event_policemenuMouseMoved

    private void policemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policemenuMouseExited
        // TODO add your handling code here:
                resetPanelBackground(policemenu);

    }//GEN-LAST:event_policemenuMouseExited

    private void profilemenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilemenuMouseMoved
        // TODO add your handling code here:
                 setPanelBackground(profilemenu);

    }//GEN-LAST:event_profilemenuMouseMoved

    private void profilemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilemenuMouseExited
        // TODO add your handling code here:
            resetPanelBackground(profilemenu);
    }//GEN-LAST:event_profilemenuMouseExited

    private void profilemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilemenuMouseClicked
        // TODO add your handling code here:
            
          try{
             
                String sql="select * from Police";
                Connection con = ConnectDatabase.connect();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                System.out.println("ExSql : "+sql);
                if(rs.next()){
                    JSONObject data = new JSONObject();
                    data.put("IdCardPolice", rs.getString("IdCardPolice"));
                    data.put("RankPolice", rs.getString("RankPolice"));
                    data.put("FirstName", rs.getString("FirstName"));
                    data.put("LastName", rs.getString("LastName"));
                    data.put("Position", rs.getString("Position"));
                 
                    PolisForm pf =new PolisForm(this,data);
                     pf.pack();
                    pf.setLocationRelativeTo(null);
                    pf.pack();
                    pf.setLocationRelativeTo(null);
                    pf.setVisible(true);
                }
                else{
                     PolisForm pf =new PolisForm(this,null);
                      pf.pack();
                pf.setLocationRelativeTo(null);
                pf.pack();
                pf.setLocationRelativeTo(null);
                    pf.setVisible(true);
                }

                rs.close();
                stmt.close();
  
            }catch(Exception ex){
                ex.printStackTrace();

            }
          data() ;
//      PolisForm pf =new PolisForm(this,null);
//                    pf.setVisible(true);
        
    }//GEN-LAST:event_profilemenuMouseClicked
   
//    private void checkdata(){
//      String sql= "select * from Police";
//            Connection con = ConnectDatabase.connect();
//          
//            try { 
//                Statement stmt = con.createStatement();
//                 ResultSet rs = stmt.executeQuery(sql);
//              if(rs.next()== false){
//               
//                     PolisForm a= new PolisForm(this, null);
//                     a.setVisible(true);
//                
//            }
//             
//    } catch (Exception e) {
//    }
//    
//    
//    }
    private void data() 
{       String a;
        String name="";
            String sql= "select * from Police";
            Connection con = ConnectDatabase.connect();
          
            try { 
                Statement stmt = con.createStatement();
                 ResultSet rs = stmt.executeQuery(sql);
              if(rs.next()){
               
                      name=rs.getString("FirstName")+" "+rs.getString("LastName");
                            
                            Data d =new Data();
                            a=rs.getString("FirstName");
//                            System.out.print(a);
        d.setPolicName(a); 
                
            }
             
    } catch (Exception e) {
    }
            UserName.setText(name);

}
    private void policemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policemenuMouseClicked
        // TODO add your handling code here:
        
                
          try{
             
                String sql="select * from PoliceStation";
                Connection con = ConnectDatabase.connect();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                System.out.println("ExSql : "+sql);
                if(rs.next()){
                    JSONObject data = new JSONObject();
                    data.put("PoliceStartionCode", rs.getString("PoliceStartionCode"));
                    data.put("PoliceStaionName", rs.getString("PoliceStaionName"));
                    data.put("PoliceStaionShort", rs.getString("PoliceStaionShort"));
                    data.put("StationAddress", rs.getString("StationAddress"));
                    data.put("StationAmphur", rs.getString("StationAmphur"));
                       data.put("StationProvince", rs.getString("StationProvince"));
                    data.put("BK", rs.getString("BK"));
                    data.put("BH", rs.getString("BH"));
                    data.put("Fax", rs.getString("Fax"));
                    data.put("TelStation", rs.getString("TelStation"));
                       data.put("PhonePolice", rs.getString("PhonePolice"));
                    data.put("HeadName", rs.getString("HeadName"));
                    data.put("HeadPosition", rs.getString("HeadPosition"));
                    data.put("HeadWorkName", rs.getString("HeadWorkName"));
                    data.put("HeadWorkPosition", rs.getString("HeadWorkPosition"));
                       data.put("CriminalCourt", rs.getString("CriminalCourt"));
                    data.put("JuvenileCourt", rs.getString("JuvenileCourt"));
                    data.put("DistrictCourt", rs.getString("DistrictCourt"));
                    data.put("MilitaryCourt", rs.getString("MilitaryCourt"));
                    data.put("AssetCourt", rs.getString("AssetCourt"));
                       data.put("LocationOfDrug", rs.getString("LocationOfDrug"));
                    data.put("CheckGun", rs.getString("CheckGun"));
                    data.put("CheckDrug", rs.getString("CheckDrug"));
                    data.put("CheckOtherExhibit", rs.getString("CheckOtherExhibit"));
                    data.put("CauseSerious", rs.getString("CauseSerious"));
                       data.put("ProvincProsecutor", rs.getString("ProvincProsecutor"));
                    data.put("ProvincProsecutorCh", rs.getString("ProvincProsecutorCh"));
                    data.put("THNumBook", rs.getString("THNumBook"));
                    data.put("ProtectChild", rs.getString("ProtectChild"));
                    data.put("StationMoo", rs.getString("StationMoo"));
                    data.put("StationTambon", rs.getString("StationTambon"));
                    data.put("Postcode", rs.getString("Postcode"));                 

                            StationForm sf = new StationForm(this,data);
                             sf.pack();
                             sf.setLocationRelativeTo(null);
                             sf.setVisible(true);
                }
                else{
                     StationForm sf = new StationForm(this,null);
                      sf.pack();
                      sf.setLocationRelativeTo(null);
                     sf.setVisible(true);
                }

                rs.close();
                stmt.close();
  
            }catch(Exception ex){
                ex.printStackTrace();

            }

    }//GEN-LAST:event_policemenuMouseClicked

    private void personmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personmenuMouseClicked
        // TODO add your handling code here:
        
         PersonOverView ps = new PersonOverView();
          ps.pack();
            ps.setLocationRelativeTo(null);
        ps.setVisible(true);
    }//GEN-LAST:event_personmenuMouseClicked

    private void howtomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtomenuMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        JDialog dialog = new JDialog(frame);//frame is owner
        JFrame in = (JFrame)(dialog.getParent());
        in.removeAll();
        InvesInformationView1 iv=new InvesInformationView1(this);
         iv.pack();
            iv.setLocationRelativeTo(null);
        iv.setVisible(true);
    }//GEN-LAST:event_howtomenuMouseClicked

    private void SueMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SueMenuMouseMoved
        // TODO add your handling code here:
        setPanelBackground(SueMenu);
    }//GEN-LAST:event_SueMenuMouseMoved

    private void SueMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SueMenuMouseClicked
        // TODO add your handling code here:
        SueCrimesOverview sf=new SueCrimesOverview();
         sf.pack();
            sf.setLocationRelativeTo(null);
        sf.setVisible(true);
    }//GEN-LAST:event_SueMenuMouseClicked

    private void SueMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SueMenuMouseExited
        // TODO add your handling code here:
             resetPanelBackground(SueMenu);
    }//GEN-LAST:event_SueMenuMouseExited

    private void SueMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SueMenuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SueMenuMousePressed

    private void SueMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SueMenuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SueMenuMouseReleased

    private void BailMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BailMenuMouseMoved
        // TODO add your handling code here:
          setPanelBackground(BailMenu);
    }//GEN-LAST:event_BailMenuMouseMoved

    private void BailMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BailMenuMouseClicked
        // TODO add your handling code here:
        BailCrimesForm bcf=new BailCrimesForm();
         bcf.pack();
            bcf.setLocationRelativeTo(null);
        bcf.setVisible(true);
    }//GEN-LAST:event_BailMenuMouseClicked

    private void BailMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BailMenuMouseExited
        // TODO add your handling code here:
         resetPanelBackground(BailMenu);
    }//GEN-LAST:event_BailMenuMouseExited

    private void BailMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BailMenuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BailMenuMousePressed

    private void BailMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BailMenuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BailMenuMouseReleased

    private void howtomenu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtomenu1MouseMoved
        // TODO add your handling code here:
          setPanelBackground(howtomenu1);
    }//GEN-LAST:event_howtomenu1MouseMoved

    private void howtomenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtomenu1MouseClicked
        // TODO add your handling code here:
//         resetPanelBackground(howtomenu1);
    }//GEN-LAST:event_howtomenu1MouseClicked

    private void howtomenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtomenu1MouseExited
        // TODO add your handling code here:
                 resetPanelBackground(howtomenu1);
    }//GEN-LAST:event_howtomenu1MouseExited

    private void jPanelSueMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSueMenuMouseClicked
        // TODO add your handling code here:
           SueCrimesOverview sf=new SueCrimesOverview();
         sf.pack();
            sf.setLocationRelativeTo(null);
        sf.setVisible(true);
        
    }//GEN-LAST:event_jPanelSueMenuMouseClicked

    private void jPanelBailMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBailMenuMouseClicked
        // TODO add your handling code here:
         BailCrimesForm bcf=new BailCrimesForm();
         bcf.pack();
            bcf.setLocationRelativeTo(null);
        bcf.setVisible(true);
    }//GEN-LAST:event_jPanelBailMenuMouseClicked

    private void jPanelDocMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDocMenuMouseClicked
        // TODO add your handling code here:
          ReportAllForm bcf=new ReportAllForm();
         bcf.pack();
            bcf.setLocationRelativeTo(null);
        bcf.setVisible(true);
    }//GEN-LAST:event_jPanelDocMenuMouseClicked
    public void setPanelBackground (JPanel jp){
        jp.setBackground(new Color(41,100,138));
    }
     public void resetPanelBackground (JPanel jp){
        jp.setBackground(new Color(4,93,179));
    }
    /**
     * @param args the command line arguments
     */
//     private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
//        try {
//            // TODO add your handling code here:
//            Image img=ImageIO.read(getClass().getResource("ur path"));
//            this.setIconImage(img);
//        } catch (IOException ex) {
//
//        }
//     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuWord().setVisible(true);
         
               
            }
        });
    }
         public void CalculateDate(){
            try{
            Connection con = ConnectDatabase.connect();
             Statement stmt = con.createStatement();
            String sqlListSuspect ="Select ArrestDateTime,CourtSuspect,Test2,NoPerson,caseIdPerson from Person where TypePerson='ผู้ต้องหา'";
             ResultSet rs = stmt.executeQuery(sqlListSuspect);
              int dateArr=0;
              String arrDateTime="";
              String noPer="";
              String caseid="";
              int total=0;
 
                    while(rs.next()){
                         arrDateTime=rs.getString("ArrestDateTime");
//                   dateArr=Integer.valueOf(aa);

                        if(rs.getString("CourtSuspect").equals("ศาลแขวง")){
                        total=6;}
                        else if(rs.getString("CourtSuspect").equals("ศาลอาญา")){
                        total=12;
                        }
                         else if(rs.getString("CourtSuspect").equals("อุจฉกรรจ์")){
                        total=12;
                        }

                        noPer=rs.getString("NoPerson");
                        caseid=rs.getString("caseIdPerson");
                           Calendar cal;
                        if(arrDateTime!=null || !"".equals(arrDateTime)){
                            System.out.println("DateOld : " +arrDateTime); 
                            Locale lc = new Locale("th","TH");
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm",lc);
                        Date date = sdf.parse(arrDateTime);
                         cal = Calendar.getInstance();
                        cal.setTime(date);                      
                        cal.add(Calendar.HOUR, +48);
                         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm",lc);
                          SimpleDateFormat dateFormat2 = new SimpleDateFormat("dd/MM/yyyy",lc);

//                        System.out.println("DateNew : "+dateFormat.format(cal.getTime()));
//                        String d1=dateFormat.format(cal.getTime());
                       
                        SimpleDateFormat  format = new SimpleDateFormat("dd/MM/yyyy HH:mm",lc);  
                        String d2Day=dateFormat.format(new Date());
                        String d24= dateFormat.format(cal.getTime());
                        Date dateTo =null;
                        Date d24Hr=null;
                         dateTo=format.parse(d2Day);
                          d24Hr=format.parse(d24);

//                       format.format(d24);

//                         dateFormat.format(dt2);
                         System.out.println("DateNew : "+d24Hr);
                        System.out.println("DateToday : "+dateTo);

                            long diff = d24Hr.getTime() - dateTo.getTime();
                           long diffSeconds = diff / 1000 % 60;  
                            long diffMinutes = diff / (60 * 1000) % 60; 
                            long diffHours = diff / (60 * 60 * 1000);
                            int diffDays = (int)(diff / (24 * 60 * 60 * 1000));
                            System.out.println("Time in seconds: " + diffSeconds + " seconds.");         
                            System.out.println("Time in minutes: " + diffMinutes + " minutes.");         
                            System.out.println("Time in hours: " + diffHours + " hours."); 
                             System.out.println("Time in Day: " + diffDays + " Days."); 

                        if(diffDays<=0 && diffHours <=0){
                           String updateSue="Update Person set SueFirst='1',SueFirstDate='"+dateFormat2.format(cal.getTime())+"',SueFirstTotal='"+total+"' where ArrestDateTime='"+arrDateTime+"'";
//                           String insertSue="insert into SueCrimeCase(SueFirst,SueFirstDate,SueFirstTotal,SueCaseId,SueSuspectId) values('1','"+dateFormat2.format(cal.getTime())+"','5','"+caseid+"','"+noPer+"')";

                             pst=con.prepareStatement(updateSue);
//                             pst=con.prepareStatement(insertSue);                                
                             pst.executeUpdate();
                             pst.close();
                        }
                        }
                    }
                 
                  
          }
            catch(Exception ex){
            ex.printStackTrace();
        }
        }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BailMenu;
    private javax.swing.JPanel SueMenu;
    private javax.swing.JLabel UserName;
    private javax.swing.JPanel formmenu;
    private javax.swing.JPanel howtomenu;
    private javax.swing.JPanel howtomenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBailMenu;
    private javax.swing.JPanel jPanelDocMenu;
    private javax.swing.JPanel jPanelSueMenu;
    private javax.swing.JPanel personmenu;
    private javax.swing.JPanel policemenu;
    private javax.swing.JPanel profilemenu;
    // End of variables declaration//GEN-END:variables
}
