/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.songkhla.wordgen;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;

/**
 *
 * @author Petpilin
 */
public class StationForm extends javax.swing.JDialog {
    
      Connection con=null;
    PreparedStatement pst=null;
    DataCase dc =new DataCase();
    boolean isInsert;

    /**
     * Creates new form StationForm
     */
    public StationForm(JFrame parrent,JSONObject datain) {
        super(parrent,true);
       initComponents();
        ImageIcon img = new ImageIcon("D://Master//WD.png");
        setIconImage(img.getImage());
        setTitle("ระบบสำนวนอิเล็คทรอนิกส์ (CRIMES)");
       if(datain != null)
       {
           
                            PoliceStationCode.setText(datain.get("PoliceStartionCode")+"");
                            PoliceStationName.setText(datain.get("PoliceStaionName")+"");
                            PoliceStationShort.setText(datain.get("PoliceStaionShort")+"");
                            StationAddress.setText(datain.get("StationAddress")+"");
                            StationAmphur.setText(datain.get("StationAmphur")+"");
                            StationProvince.setText(datain.get("StationProvince")+"");
                            BK.setText(datain.get("BK")+"");
                            BH.setText(datain.get("BH")+"");
                            Fax.setText(datain.get("Fax")+"");
                            TelStation.setText(datain.get("TelStation")+"");
                            PhonePolice.setText(datain.get("PhonePolice")+"");
                            HeadName.setText(datain.get("HeadName")+"");
                            HeadPosition.setText(datain.get("HeadPosition")+"");
                            HeadWorkName.setText(datain.get("HeadWorkName")+"");
                            HeadWorkPosition.setText(datain.get("HeadWorkPosition")+"");
                            CriminalCourt.setText(datain.get("CriminalCourt")+"");
                            JuvenileCourt.setText(datain.get("JuvenileCourt")+"");
                            DistrictCourt.setText(datain.get("DistrictCourt")+"");
                            MilitaryCourt.setText(datain.get("MilitaryCourt")+"");
                            AssetCourt.setText(datain.get("AssetCourt")+"");
                            LocationOfD.setText(datain.get("LocationOfDrug")+"");
                            CheckGun.setText(datain.get("CheckGun")+"");
                            CheckDrug.setText(datain.get("CheckDrug")+"");
                            CheckOtherExhibit.setText(datain.get("CheckOtherExhibit")+"");
                            CauseSerious.setText(datain.get("CauseSerious")+"");
                            ProvincProsecutor.setText(datain.get("ProvincProsecutor")+"");
                            ProvincProsecutorCh.setText(datain.get("ProvincProsecutorCh")+"");
                            THNumBook.setText(datain.get("THNumBook")+"");
                            ProtectChild.setText(datain.get("ProtectChild")+"");
                            StationMoo.setText(datain.get("StationMoo")+"");
                            StationTambon.setText(datain.get("StationTambon")+"");
                            Postcode.setText(datain.get("Postcode")+"");
       }
       else{
       isInsert=true;
       }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PoliceStationCode = new javax.swing.JTextField();
        PoliceStationName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PoliceStationShort = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        StationAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        StationMoo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BK = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BH = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        StationTambon = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        StationAmphur = new javax.swing.JTextField();
        StationProvince = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Postcode = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TelStation = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        PhonePolice = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        HeadName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        HeadPosition = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        HeadWorkName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        HeadWorkPosition = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        CriminalCourt = new javax.swing.JTextField();
        JuvenileCourt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        DistrictCourt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        MilitaryCourt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        AssetCourt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        LocationOfD = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        CheckGun = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        CheckDrug = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        CheckOtherExhibit = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        CauseSerious = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        ProtectChild = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        ProvincProsecutor = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        ProvincProsecutorCh = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        THNumBook = new javax.swing.JTextField();
        jButtonSaveStation = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        Fax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ข้อมูลหน่วยงานและหน่วยงานที่เกี่ยวข้อง");
        setPreferredSize(new java.awt.Dimension(1264, 726));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(4, 93, 179));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("TH SarabunPSK", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ข้อมูลหน่วยงานและหน่วยงานที่เกี่ยวข้อง");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(946, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel8.setText("รหัสสถานีตำรวจ");

        PoliceStationCode.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        PoliceStationCode.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PoliceStationCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoliceStationCodeActionPerformed(evt);
            }
        });
        PoliceStationCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PoliceStationCodeKeyTyped(evt);
            }
        });

        PoliceStationName.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel9.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel9.setText("ชื่อหน่วยงาน");

        jLabel10.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel10.setText("ชื่อหน่วยงาน(ย่อ)");

        PoliceStationShort.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel11.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel11.setText("ที่อยู่");

        StationAddress.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel12.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel12.setText("หมู่");

        StationMoo.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel13.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel13.setText("กองบังคับการ ตร.ภ.จว.");

        BK.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel14.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel14.setText("กองบัญชาการ ภาค");

        BH.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel15.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel15.setText("ตำบล/แขวง");

        StationTambon.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel16.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel16.setText("อำเภอ/เขต");

        StationAmphur.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        StationProvince.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel17.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel17.setText("จังหวัด");

        jLabel18.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel18.setText("รหัสไปรษณีย์");

        Postcode.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        Postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PostcodeKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel19.setText("เบอร์โทรศัพท์(สถานี)");

        TelStation.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        TelStation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelStationKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel20.setText("เบอร์โทรศัพท์(มือถือ)");

        PhonePolice.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        PhonePolice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhonePoliceKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel21.setText("โทรสาร");

        HeadName.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel22.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel22.setText("ตำแหน่งหัวหน้าหน่วย");

        HeadPosition.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel23.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel23.setText("ชื่อหัวหน้างาน");

        HeadWorkName.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel24.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel24.setText("ตำแหน่งหัวหน้างาน");

        HeadWorkPosition.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel25.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel25.setText("ศาลจังหวัดอาญา");

        CriminalCourt.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        JuvenileCourt.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel26.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel26.setText("ศาลเยาวชน");

        jLabel27.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel27.setText("ศาลแขวง");

        DistrictCourt.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel28.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel28.setText("ศาลทหาร");

        MilitaryCourt.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel29.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel29.setText("ศาลทรัพย์สินทางปัญญาและการค้าระหว่างประเทศ");

        AssetCourt.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel30.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel30.setText("สถานที่ส่งยาเสพติดตรวจ");

        LocationOfD.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        LocationOfD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationOfDActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel31.setText("สถานที่ี่ตรวจปืนกระสุน ระเบิด");

        CheckGun.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel32.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel32.setText("สถานที่ตรวจสารคัดหลั่งในร่างกายตรวจหาสารเสพติด");

        CheckDrug.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel33.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel33.setText("สถานที่ส่่งตรวจของกลางอื่น");

        CheckOtherExhibit.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel34.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel34.setText("รายงานเหตุอุกฉกรรจ์หรือเหตุที่ต้องรายงาน ไปยัง");

        CauseSerious.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel35.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel35.setText("สถานพินิจคุ้มครองเด็กและเยาวชน");

        ProtectChild.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel36.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel36.setText("อัยการจังหวัด");

        ProvincProsecutor.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel37.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel37.setText("อัยการจังหวัด(คดีเยาวชน)");

        ProvincProsecutorCh.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jLabel38.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel38.setText("ตช เลขหนังสือ");

        THNumBook.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jButtonSaveStation.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jButtonSaveStation.setText("บันทึก");
        jButtonSaveStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveStationActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel40.setText("ชื่อหัวหน้าหน่วย");

        Fax.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(jButtonSaveStation, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(70, 70, 70))
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(310, 310, 310)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StationTambon, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TelStation, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HeadName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(9, 9, 9)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(JuvenileCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(MilitaryCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(HeadPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(HeadWorkPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(PhonePolice, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(StationAmphur, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel17)
                                                            .addGap(45, 45, 45)
                                                            .addComponent(StationProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel38)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(THNumBook, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ProvincProsecutor))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel34)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CauseSerious))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CheckDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel37)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ProvincProsecutorCh))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ProtectChild, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(PoliceStationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PoliceStationShort, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(StationAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(StationMoo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(BK, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(20, 20, 20)
                                                            .addComponent(jLabel14)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(BH, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(PoliceStationName, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jLabel15)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel19))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel40))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(DistrictCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(CriminalCourt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                                                    .addComponent(HeadWorkName, javax.swing.GroupLayout.Alignment.LEADING)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel24)
                                                .addComponent(jLabel26)
                                                .addComponent(jLabel28))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LocationOfD, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AssetCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckGun, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckOtherExhibit)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PoliceStationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PoliceStationName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PoliceStationShort, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StationAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StationMoo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StationAmphur, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StationProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StationTambon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelStation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhonePolice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(THNumBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeadName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeadPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeadWorkPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeadWorkName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CriminalCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JuvenileCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MilitaryCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DistrictCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssetCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckGun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationOfD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOtherExhibit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProtectChild, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CauseSerious, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProvincProsecutorCh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProvincProsecutor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButtonSaveStation)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveStationActionPerformed
        con=ConnectDatabase.connect();
           //Connection con = ConnectDatabase.connect();
      
              if(isInsert){
                     int dialogResult = JOptionPane.showConfirmDialog (null, "ทำการบันทึกข้อมูล?", "ยืนยันการบันทึกข้อมูล",JOptionPane.YES_NO_OPTION);
                    if(dialogResult == JOptionPane.YES_OPTION){
          try {  
              Statement stmt = con.createStatement();
     
        String sql="INSERT INTO PoliceStation (PoliceStartionCode,PoliceStaionName,PoliceStaionShort,StationAddress,StationAmphur,StationProvince,BK," +
        "BH,TelStation,PhonePolice,Fax,HeadName,HeadPosition,HeadWorkName,HeadWorkPosition,CriminalCourt,JuvenileCourt,DistrictCourt," +
        "MilitaryCourt,AssetCourt,LocationOfDrug,CheckGun,CheckDrug,CheckOtherExhibit,CauseSerious,ProvincProsecutor,ProvincProsecutorCh," +
        "THNumBook,ProtectChild,StationTambon,StationMoo,Postcode) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
   pst=con.prepareStatement(sql);
            pst.setString(1,PoliceStationCode.getText());
            pst.setString(2,PoliceStationName.getText());
            pst.setString(3,PoliceStationShort.getText());
            pst.setString(4,StationAddress.getText());
            pst.setString(5,StationAmphur.getText());
            pst.setString(6,StationProvince.getText());
            pst.setString(7,BK.getText());
            pst.setString(8,BH.getText());
            pst.setString(9,TelStation.getText());
            pst.setString(10,PhonePolice.getText());
            pst.setString(11,Fax.getText());
            pst.setString(12,HeadName.getText());
            pst.setString(13,HeadPosition.getText());
            pst.setString(14,HeadWorkName.getText());
            pst.setString(15,HeadWorkPosition.getText());
            pst.setString(16,CriminalCourt.getText());
            pst.setString(17,JuvenileCourt.getText());
            pst.setString(18,DistrictCourt.getText());
            pst.setString(19,MilitaryCourt.getText());
            pst.setString(20,AssetCourt.getText());
            pst.setString(21,LocationOfD.getText());
            pst.setString(22,CheckGun.getText());
            pst.setString(23,CheckDrug.getText());
            pst.setString(24,CheckOtherExhibit.getText());
            pst.setString(25,CauseSerious.getText());
            pst.setString(26,ProvincProsecutor.getText());
            pst.setString(27,ProvincProsecutorCh.getText());
            pst.setString(28,THNumBook.getText());
            pst.setString(29,ProtectChild.getText());
            pst.setString(30,StationTambon.getText());
            pst.setString(31,StationMoo.getText());
            pst.setString(32,Postcode.getText());
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Saved successfully");
             setVisible(false);
              } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println("SQL : "+pst);
        }
              }
              }
              else{
                      int dialogResult = JOptionPane.showConfirmDialog (null, "ทำการแก้ไขข้อมูล?", "ยืนยันการแก้ไขข้อมูล",JOptionPane.YES_NO_OPTION);
          if(dialogResult == JOptionPane.YES_OPTION){
         try{
         String sqlUpdate= "UPDATE PoliceStation Set\n "
        + "PoliceStartionCode=?,"
        + "PoliceStaionName=?,"
        + "PoliceStaionShort=?,"
        + "StationAddress=?,"
        + "StationAmphur=?,"
        + "StationProvince=?,"
        + "BK=?,"
        + "BH=?,"
        + "TelStation=?,"
        + "PhonePolice=?,"
        + "Fax=?,"
        + "HeadName=?,"
        + "HeadPosition=?,"
        + "HeadWorkName=?,"
        + "HeadWorkPosition=?,"
        + "CriminalCourt=?,"
        + "JuvenileCourt=?,"
        + "DistrictCourt=?,"
        + "MilitaryCourt=?,"
        + "AssetCourt=?,"
        + "LocationOfDrug=?,"
        + "CheckGun=?,"
        + "CheckDrug=?,"
        + "CheckOtherExhibit=?,"
        + "CauseSerious=?,"
        + "ProvincProsecutor=?,"
        + "ProvincProsecutorCh=?,"
        + "THNumBook=?,"
        + "ProtectChild=?,"
        + "StationTambon=?,"
        + "StationMoo=?,"
        + "Postcode=? "
        + "Where PoliceStartionCode=?";
      System.out.println("SQL : "+sqlUpdate);
            pst=con.prepareStatement(sqlUpdate);
            pst.setString(1,PoliceStationCode.getText());
            pst.setString(2,PoliceStationName.getText());
            pst.setString(3,PoliceStationShort.getText());
            pst.setString(4,StationAddress.getText());
            pst.setString(5,StationAmphur.getText());
            pst.setString(6,StationProvince.getText());
            pst.setString(7,BK.getText());
            pst.setString(8,BH.getText());
            pst.setString(9,TelStation.getText());
            pst.setString(10,PhonePolice.getText());
            pst.setString(11,Fax.getText());
            pst.setString(12,HeadName.getText());
            pst.setString(13,HeadPosition.getText());
            pst.setString(14,HeadWorkName.getText());
            pst.setString(15,HeadWorkPosition.getText());
            pst.setString(16,CriminalCourt.getText());
            pst.setString(17,JuvenileCourt.getText());
            pst.setString(18,DistrictCourt.getText());
            pst.setString(19,MilitaryCourt.getText());
            pst.setString(20,AssetCourt.getText());
            pst.setString(21,LocationOfD.getText());
            pst.setString(22,CheckGun.getText());
            pst.setString(23,CheckDrug.getText());
            pst.setString(24,CheckOtherExhibit.getText());
            pst.setString(25,CauseSerious.getText());
            pst.setString(26,ProvincProsecutor.getText());
            pst.setString(27,ProvincProsecutorCh.getText());
            pst.setString(28,THNumBook.getText());
            pst.setString(29,ProtectChild.getText());
            pst.setString(30,StationTambon.getText());
            pst.setString(31,StationMoo.getText());
            pst.setString(32,Postcode.getText());
             pst.setString(33,PoliceStationCode.getText());
             System.out.println("SQL : "+sqlUpdate);
            pst.executeUpdate();
            pst.close();
             setVisible(false);
              
                    }
            
             catch (Exception e) {
           JOptionPane.showMessageDialog(null, "บันทึกข้อมูลเรียบร้อยแล้ว");
            System.out.println("SQL : "+pst);
            
        }
              }
        setVisible(false);
              }
    }//GEN-LAST:event_jButtonSaveStationActionPerformed

    private void LocationOfDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationOfDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationOfDActionPerformed

    private void PoliceStationCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoliceStationCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoliceStationCodeActionPerformed

    private void PoliceStationCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PoliceStationCodeKeyTyped
        char vChar = evt.getKeyChar();
         if(!(Character.isDigit(vChar) || (vChar==KeyEvent.VK_BACK_SPACE)||(vChar==KeyEvent.VK_DELETE)))
         {
             evt.consume();
         }
         if(PoliceStationCode.getText().length()>=5) {  
           evt.consume(); // TODO add your han
        }
  
    }//GEN-LAST:event_PoliceStationCodeKeyTyped

    private void PostcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PostcodeKeyTyped
         char vChar = evt.getKeyChar();
         if(!(Character.isDigit(vChar) || (vChar==KeyEvent.VK_BACK_SPACE)||(vChar==KeyEvent.VK_DELETE)))
         {
             evt.consume();
         }
        if(Postcode.getText().length()>=5) {  
            evt.consume();        
            }
    }//GEN-LAST:event_PostcodeKeyTyped

    private void PhonePoliceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhonePoliceKeyTyped

        if(PhonePolice.getText().length()>=10) {  
           evt.consume();  
         }// TODO add your handling code here:
    }//GEN-LAST:event_PhonePoliceKeyTyped

    private void TelStationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelStationKeyTyped
       if(TelStation.getText().length()>=10) {  
           evt.consume();  
         } // TODO add your handling code here:
    }//GEN-LAST:event_TelStationKeyTyped
private void data() 
{
            String sql= "select * from PoliceStation";
            Connection con = ConnectDatabase.connect();
            try {  Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
              if(rs.next()){
                  
               
                            PoliceStationCode.setText(rs.getString("PoliceStartionCode"));
                            PoliceStationName.setText(rs.getString("PoliceStaionName"));
                            PoliceStationShort.setText(rs.getString("PoliceStaionShort"));
                            StationAddress.setText(rs.getString("StationAddress"));
                            StationAmphur.setText(rs.getString("StationAmphur"));
                            StationProvince.setText(rs.getString("StationProvince"));
                            BK.setText(rs.getString("BK"));
                            BH.setText(rs.getString("BH"));
                            Fax.setText(rs.getString("Fax"));
                            TelStation.setText(rs.getString("TelStation"));
                            PhonePolice.setText(rs.getString("PhonePolice"));
                            HeadName.setText(rs.getString("HeadName"));
                            HeadPosition.setText(rs.getString("HeadPosition"));
                            HeadWorkName.setText(rs.getString("HeadWorkName"));
                            HeadWorkPosition.setText(rs.getString("HeadWorkPosition"));
                            CriminalCourt.setText(rs.getString("CriminalCourt"));
                            JuvenileCourt.setText(rs.getString("JuvenileCourt"));
                            DistrictCourt.setText(rs.getString("DistrictCourt"));
                            MilitaryCourt.setText(rs.getString("MilitaryCourt"));
                            AssetCourt.setText(rs.getString("AssetCourt"));
                            LocationOfD.setText(rs.getString("LocationOfDrug"));
                            CheckGun.setText(rs.getString("CheckGun"));
                            CheckDrug.setText(rs.getString("CheckDrug"));
                            CheckOtherExhibit.setText(rs.getString("CheckOtherExhibit"));
                            CauseSerious.setText(rs.getString("CauseSerious"));
                            ProvincProsecutor.setText(rs.getString("ProvincProsecutor"));
                            ProvincProsecutorCh.setText(rs.getString("ProvincProsecutorCh"));
                            THNumBook.setText(rs.getString("THNumBook"));
                            ProtectChild.setText(rs.getString("ProtectChild"));
                            StationMoo.setText(rs.getString("StationMoo"));
                            StationTambon.setText(rs.getString("StationTambon"));
                            Postcode.setText(rs.getString("Postcode"));

                
            }
    } catch (Exception e) {
    }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new StationForm().setVisible(true);
            }
        });
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssetCourt;
    private javax.swing.JTextField BH;
    private javax.swing.JTextField BK;
    private javax.swing.JTextField CauseSerious;
    private javax.swing.JTextField CheckDrug;
    private javax.swing.JTextField CheckGun;
    private javax.swing.JTextField CheckOtherExhibit;
    private javax.swing.JTextField CriminalCourt;
    private javax.swing.JTextField DistrictCourt;
    private javax.swing.JTextField Fax;
    private javax.swing.JTextField HeadName;
    private javax.swing.JTextField HeadPosition;
    private javax.swing.JTextField HeadWorkName;
    private javax.swing.JTextField HeadWorkPosition;
    private javax.swing.JTextField JuvenileCourt;
    private javax.swing.JTextField LocationOfD;
    private javax.swing.JTextField MilitaryCourt;
    private javax.swing.JTextField PhonePolice;
    private javax.swing.JTextField PoliceStationCode;
    private javax.swing.JTextField PoliceStationName;
    private javax.swing.JTextField PoliceStationShort;
    private javax.swing.JTextField Postcode;
    private javax.swing.JTextField ProtectChild;
    private javax.swing.JTextField ProvincProsecutor;
    private javax.swing.JTextField ProvincProsecutorCh;
    private javax.swing.JTextField StationAddress;
    private javax.swing.JTextField StationAmphur;
    private javax.swing.JTextField StationMoo;
    private javax.swing.JTextField StationProvince;
    private javax.swing.JTextField StationTambon;
    private javax.swing.JTextField THNumBook;
    private javax.swing.JTextField TelStation;
    private javax.swing.JButton jButtonSaveStation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
